flyway.url=jdbc:postgresql://localhost:5432/agendamento
flyway.user=postgres
flyway.password=Larissa9*
flyway.locations=classpath:db/migration
flyway.baselineOnMigrate=true
flyway.cleanDisabled=false

